### PR TITLE
Copyright statement updated to cover year 2021. Issue #239.

### PR DESCRIPTION
**Pull request by kirjaamo**
Copyright statements changed to 2021.

### CODE REVIEW

**Review by byte — CHANGES_REQUESTED** [review]
Looks good, things are modern, however it seems like you have missed the layout template, add that and it could be merged

**Review by byte — CHANGES_REQUESTED** [review]
Looks good, things are modern, however it seems like you have missed the layout template, add that and it could be merged

**Comment by kirjaamo** [comment]
The layout template is now updated.

**Review by byte — APPROVED** [review]
This looks good

**Review by byte — APPROVED** [review]
This looks good

**Comment by kirjaamo** [comment]
Implemented and published.

**Pull request closed without merging**
