### PR TITLE
Issue #187. Starting commands for MariaDB and XDB were added.

### PR DESCRIPTION
**Pull request by kirjaamo**
New commands added for Colin to check.

### CODE REVIEW

**Review by byte — CHANGES_REQUESTED** [review]
it is mostly good

can you check what is galera_new_cluster_sh ?

I also think for mariadb, just say use galera_new_cluster in the intro. talk about older versions later, but most people are going to use the above

**Comment by kirjaamo** [comment]
Grooverdan mentioned galera_new_cluster_sh in his first issue report. I thought that's the command for Percona. Maybe it's not, as I could not find it in Percona documentation. What is the correct command for Percona on systemd systems?

**Review by byte — CHANGES_REQUESTED** [review]
It is: galera_new_cluster (it refers to galera_new_cluster.sh and not galera_new_cluster_sh -- note the . vs _)

**Comment by kirjaamo** [comment]
Fixed.

**Review by byte — CHANGES_REQUESTED** [review]
Only in MariaDB do you use: galera_new_cluster

On PXC you use: systemctl start mysql@bootstrap.service

(source) https://www.percona.com/doc/percona-xtradb-cluster/LATEST/bootstrap.html

Also, please say Percona XtraDB Cluster not "Percona XtraDB" -- XtraDB is Percona's branch of InnoDB (see: https://en.wikipedia.org/wiki/XtraDB) -- this refers to a storage engine not their cluster product

**Comment by kirjaamo** [comment]
OK, a new push

**Comment by kirjaamo** [comment]
OK, let's merge and close the ticket.

**Review by byte — APPROVED** [review]
OK, approved

**Pull request merged**
