### PR TITLE
Issue #227

### PR DESCRIPTION
**Pull request by kirjaamo**
Mariabackup added. The cpat option description updated.

### CODE REVIEW

**Review by byte — CHANGES_REQUESTED** [review]
Xtrabackup-v2? For completeness

**Comment by kirjaamo** [comment]
It seems that _XtraBackup Parameters_ section actually talks about XtraBackup-v2 parameters. Should we just rename the section as _XtraBackup-v2 Parameters_?

**Comment by byte** [comment]
> It seems that _XtraBackup Parameters_ section actually talks about XtraBackup-v2 parameters. Should we just rename the section as _XtraBackup-v2 Parameters_?

We actually only use xtrabackup-v2 these days, I do not know why xtrabackup itself exists, so go ahead

**Review by byte — APPROVED** [review]
ok

**Pull request merged**
