### PR TITLE
Support for debian 11

### PR DESCRIPTION
**Pull request by kirjaamo**

### CODE REVIEW

**Review by byte — COMMENTED** [review]
Can you check about CentOS 8. Red Hat Enterprise Linux is not mentioned, and CentOS 8 is now EOL to CentOS Stream, so even the main Galera Cluster database is now basically CentOS 7 and RHEL8 (with no guarantee that it runs on CentOS Stream)

**Comment by kirjaamo** [comment]
Red Hat Enterprise Linux is mentioned in two places:
- Red Hat Enterprise Linux is supported with binary packages
- There is an example: "For example, ``rhel6-amd64`` would reference packages for a Red Hat Enterprise Linux 6 server running on 64-bit hardware."
CentOS 8 mentioned once:
- Please note that on CentOS 8 and RedHat 8, you need to disable MySQL and MariaDB modules before installing Galera Cluster

Should I replace Red Hat Enterprise Linux with something else? For CentOS 8, whould I replace it with CentOS 7 or Stream?

**Review by byte — APPROVED** [review]
Ok. But please also check the RHEL 8 that we support

**Comment by kirjaamo** [comment]
RHEL8 is ok, if the version number is mentioned, it is 8

**Comment by byte** [comment]
@kirjaamo we now even have a tool to tell you more about this

./gm-installer version --list-supported-oses
gm-installer version 1.13.0 (linux/amd64)
Supported OSes:
	centos:7:	deprecated
	debian:10:	deprecated
	debian:11:	active
	debian:12:	active
	redhat:8:	active
	ubuntu:20.04:	active
	ubuntu:22.04:	active

This is the list of supported OSes. Deprecated means will be removed in future, but currently, this is quite a long list of supported install options

**Review by byte — APPROVED** [review]
approve/merge this because we have to make more changes shortly (this is already outdated)

**Pull request merged**
