### PR TITLE
Issue #265

### PR DESCRIPTION
**Pull request by kirjaamo**
Banners and a test link were added.

### CODE REVIEW

**Review by byte — APPROVED** [review]
makes sense, we should have done this a while ago; are we only going to add it to one page though? why not more pages?

**Comment by kirjaamo** [comment]
There will be more banners. I'm just struggling to get it to work on one page first.

**Review by byte — APPROVED** [review]
Looking good

**Comment by kirjaamo** [comment]
@byte I have added the banners to PDF and HTML versions now. Can you review and approve | comment, please.

**Review by byte — APPROVED** [review]
@kirjaamo as long as it builds in the docs system and is syntatically correct, i am approving it.

**Pull request merged**
