### PR TITLE
Issue #206. Crash recovery information added.

### PR DESCRIPTION
**Pull request by kirjaamo**
I made a pull request to test the content in a browser. If a real review is required, I'll send a message in Slack.

### CODE REVIEW

**Review by byte — CHANGES_REQUESTED** [review]
This is far too close to the percona documentation, so we can't take it and copyright it...

beyond that:

- do we use Node A, B, C? I feel we use node 1,2,3 (maybe now is a good time to come up with a style guide)
- systemctl start mysql@bootstrap.service <-- pxc only, this does not work on codership galera
- i think the examples around sysbench (test.sbtest1) need to be reworked for us

so while the doc is "good", because it came from https://www.percona.com/doc/percona-xtradb-cluster/LATEST/howtos/crash-recovery.html -- we cannot adopt it as is

**Comment by kirjaamo** [comment]
- So, I add the link to the blog (see Slack).
- I replace A, B anC with 1, 2 and 3.
- What is the command that works on Galera?
- What needs to be done with the sysbench examples?

**Comment by byte** [comment]
> * So, I add the link to the blog (see Slack).

OK, good on the link to the blog. Please also double check with sakari if this is ok

> * I replace A, B and C with 1, 2 and 3.

OK

> * What is the command that works on Galera?

mysqld_bootstrap --wsrep-new-cluster
(this works with mysql8 codership; please remember that this is different for mariabd and pxc)

> * What needs to be done with the sysbench examples?

No need to change if it was based on the blog

**Comment by kirjaamo** [comment]
About mysqld_bootstrap --wsrep-new-cluster, should we also mention commands for MariaDB and PXC?

**Review by byte — APPROVED** [review]
OK, this is good, and the attribution is agreed as ok

**Pull request merged**
