### PR TITLE
Issue #331

### PR DESCRIPTION
**Pull request by kirjaamo**
wsrep_applier_threads recommended instead of wsrep_slave_threads.

### CODE REVIEW

**Review by byte — COMMENTED** [review]
I want to approve it, but cannot just yet. Because we still need to *reference* wsrep_slave_threads -- it is current and in use everywhere, until MySQL 8.0.26 release.

Our documentation has to be usable for everyone including those using MySQL 5.7 and before.

This is why it is not a :%s/wsrep_slave_threads/wsrep_applier_threads/g kind of scenario. 

We have a majority of users who will try wsrep_applier_threads and find that it *fails* because their earlier releases only support wsrep_slave_threads.

BTW, another change you should incorporate, is to go thru the docs for wsrep_restart_slave which is now as of 8.0.26 wsrep_restart_replica.

Again, you cannot just do a find and replace.

**Comment by kirjaamo** [comment]
wsrep_restart_slave is only mentioned in section MySQL wsrep Options. It is also stated that it is deprecated.

**Comment by byte** [comment]
> wsrep_restart_slave is only mentioned in section MySQL wsrep Options. It is also stated that it is deprecated.

I still think the first part of my comment isn't addressed though. wsrep_slave_threads is applicable to every galera before 8.0.26. How can we share both the information, preferring wsrep_applier_threads, but also not losing out on the fact that for man people wsrep_slave_threads is the right way to go?

**Comment by kirjaamo** [comment]
Another suggestion pushed.

**Review by byte — APPROVED** [review]
ok to push

**Pull request merged**
