### PR TITLE
Issue #254. Added a note that this is an optional feature.

### PR DESCRIPTION
**Pull request by kirjaamo**
Also, the server options are now in alphabetical order.

### CODE REVIEW

**Review by byte — COMMENTED** [review]
I want to make clear that I have not tried wsrep_mode=replicate_aria yet, because this stuff is in 10.6 which is unreleased. So we might want to make it clear that it is documentation for unreleased software

I would also pay attention to https://mariadb.com/kb/en/mariadb-1060-release-notes/

Galera
wsrep_mode variable for turning on WSREP features which are not part of default behavior.
wsrep_strict_ddl has been deprecated. Use wsrep_mode=STRICT_REPLICATION instead.

**Comment by kirjaamo** [comment]
Do you want me to expand out _wsrep_mode_ description (https://galeracluster.com/documentation/html_docs_20210312-1454-mariadb_options_2/documentation/mysql-wsrep-options.html?highlight=wsrep_mode#wsrep-mode) to cover the MariaDB options (https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_mode). Or should I add the MariaDB options to the _MariaDB Options_ page?

**Review by byte — APPROVED** [review]
This is OK

**Comment by byte** [comment]
> Do you want me to expand out _wsrep_mode_ description (https://galeracluster.com/documentation/html_docs_20210312-1454-mariadb_options_2/documentation/mysql-wsrep-options.html?highlight=wsrep_mode#wsrep-mode) to cover the MariaDB options (https://mariadb.com/kb/en/galera-cluster-system-variables/#wsrep_mode). Or should I add the MariaDB options to the _MariaDB Options_ page?

For lack of confusion, let us just keep this at MariaDB Server options. Otherwise people coming to our page will also wonder why the feature doesn't work in our release. For example, we don't even ship the Aria storage engine

**Pull request merged**
